"""Shared persistence logic for the HTTP server and the Native Messaging host.

A single payload sent by the extension is normalised to three on-disk
representations so that any agent / shell tool can consume cookies without
custom adapters:

* ``cookies.txt``         – Netscape format (curl, wget, yt-dlp, requests)
* ``cookies.json``        – Full cookie metadata array
* ``storage_state.json``  – Playwright-compatible (cookies + localStorage)
* ``raw.json``            – The raw payload (for debugging / future formats)

All files are written atomically with mode 0600 in a directory created with
mode 0700.
"""

from __future__ import annotations

import json
import os
import stat
import tempfile
import time
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlparse

DEFAULT_BASE_DIR = Path(os.environ.get("CERT_KEEPER_HOME", "~/.my-cert")).expanduser()


# ---------------------------------------------------------------------------
# Filesystem helpers
# ---------------------------------------------------------------------------

def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(path, stat.S_IRWXU)  # 0700
    except OSError:
        pass


def _atomic_write(path: Path, data: str) -> None:
    """Write ``data`` to ``path`` atomically with permission 0600."""
    _ensure_dir(path.parent)
    fd, tmp = tempfile.mkstemp(prefix=".tmp-", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(data)
        try:
            os.chmod(tmp, stat.S_IRUSR | stat.S_IWUSR)  # 0600
        except OSError:
            pass
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# ---------------------------------------------------------------------------
# Format converters
# ---------------------------------------------------------------------------

def _origin(url: str) -> str:
    p = urlparse(url)
    return f"{p.scheme}://{p.netloc}"


def _domain(url: str) -> str:
    return urlparse(url).hostname or ""


def _cookie_dicts(payload: dict[str, Any]) -> list[dict[str, Any]]:
    """Return cookies as list of dicts.

    The extension may send either a structured ``cookies_detail`` array or a
    plain ``cookies`` string of the form ``"k1=v1; k2=v2"``.  We support both
    so old extension builds keep working.
    """
    if isinstance(payload.get("cookies_detail"), list):
        return [dict(c) for c in payload["cookies_detail"] if isinstance(c, dict)]

    raw = payload.get("cookies")
    if not isinstance(raw, str) or not raw.strip():
        return []
    domain = _domain(payload.get("url", ""))
    out: list[dict[str, Any]] = []
    for part in raw.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, value = part.split("=", 1)
        out.append({
            "name": name.strip(),
            "value": value.strip(),
            "domain": domain,
            "path": "/",
            "secure": True,
            "httpOnly": False,
        })
    return out


def to_netscape(cookies: Iterable[dict[str, Any]]) -> str:
    """Serialize cookies to Netscape ``cookies.txt`` format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by cert-keeper. Do not edit.",
        "",
    ]
    for c in cookies:
        domain = c.get("domain") or ""
        # Leading dot => include subdomains, mirroring Chrome's hostOnly flag
        host_only = not domain.startswith(".") and not c.get("hostOnly", False)
        flag = "FALSE" if host_only else "TRUE"
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        # Chrome may report 0 / -1 / None for session cookies
        exp = int(c.get("expirationDate") or c.get("expires") or 0)
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([domain, flag, path, secure, str(exp), name, value]))
    lines.append("")
    return "\n".join(lines)


_PW_SAMESITE = {"strict": "Strict", "lax": "Lax", "no_restriction": "None", "none": "None", "unspecified": "Lax"}


def to_storage_state(payload: dict[str, Any], cookies: list[dict[str, Any]]) -> dict[str, Any]:
    """Build a Playwright-compatible ``storage_state.json`` body."""
    pw_cookies = []
    for c in cookies:
        same_site = str(c.get("sameSite") or "lax").lower()
        entry = {
            "name": c.get("name", ""),
            "value": c.get("value", ""),
            "domain": c.get("domain", ""),
            "path": c.get("path") or "/",
            "secure": bool(c.get("secure", False)),
            "httpOnly": bool(c.get("httpOnly", False)),
            "sameSite": _PW_SAMESITE.get(same_site, "Lax"),
        }
        exp = c.get("expirationDate") or c.get("expires")
        if exp:
            entry["expires"] = float(exp)
        pw_cookies.append(entry)

    origins: list[dict[str, Any]] = []
    ls = payload.get("localStorage") or {}
    if ls:
        origins.append({
            "origin": _origin(payload.get("url", "")),
            "localStorage": [{"name": k, "value": v} for k, v in ls.items()],
        })
    return {"cookies": pw_cookies, "origins": origins}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def save_site(payload: dict[str, Any], base_dir: Path | None = None) -> dict[str, Any]:
    """Persist a payload received from the extension. Returns a summary dict."""
    base = Path(base_dir or DEFAULT_BASE_DIR).expanduser()
    site_id = payload.get("site_id") or "unknown"
    if not isinstance(site_id, str) or not site_id.replace("-", "").replace("_", "").isalnum():
        raise ValueError(f"invalid site_id: {site_id!r}")

    site_dir = base / site_id
    _ensure_dir(site_dir)

    cookies = _cookie_dicts(payload)
    _atomic_write(site_dir / "cookies.txt", to_netscape(cookies))
    _atomic_write(site_dir / "cookies.json", json.dumps(cookies, indent=2, ensure_ascii=False))
    _atomic_write(
        site_dir / "storage_state.json",
        json.dumps(to_storage_state(payload, cookies), indent=2, ensure_ascii=False),
    )
    raw = dict(payload)
    raw["_saved_at"] = int(time.time())
    _atomic_write(site_dir / "raw.json", json.dumps(raw, indent=2, ensure_ascii=False))

    return {
        "site_id": site_id,
        "cookie_count": len(cookies),
        "ls_count": len(payload.get("localStorage") or {}),
        "path": str(site_dir),
    }


def save_recording(payload: dict[str, Any], base_dir: Path | None = None) -> dict[str, Any]:
    """Persist an API recording payload."""
    base = Path(base_dir or DEFAULT_BASE_DIR).expanduser()
    rec_dir = base / "_recordings"
    _ensure_dir(rec_dir)
    name = payload.get("name") or f"recording-{int(time.time())}"
    safe = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in str(name))[:80]
    path = rec_dir / f"{safe}.json"
    _atomic_write(path, json.dumps(payload, indent=2, ensure_ascii=False))
    return {"path": str(path), "request_count": len(payload.get("requests") or [])}


def list_sites(base_dir: Path | None = None) -> list[dict[str, Any]]:
    base = Path(base_dir or DEFAULT_BASE_DIR).expanduser()
    if not base.exists():
        return []
    out: list[dict[str, Any]] = []
    for entry in sorted(base.iterdir()):
        if not entry.is_dir() or entry.name.startswith("_"):
            continue
        raw_file = entry / "raw.json"
        info: dict[str, Any] = {"site_id": entry.name, "path": str(entry)}
        if raw_file.exists():
            try:
                with raw_file.open(encoding="utf-8") as fh:
                    raw = json.load(fh)
                info["saved_at"] = raw.get("_saved_at")
                info["url"] = raw.get("url")
                info["cookie_count"] = len(_cookie_dicts(raw))
            except Exception:
                pass
        out.append(info)
    return out
